"""add_is_flag_regex_column_to_ctfs

Revision ID: e2f72b1ae5f3
Revises: 73af1314d471
Create Date: 2025-12-30 10:02:36.532881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2f72b1ae5f3'
down_revision: Union[str, None] = '73af1314d471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'ctf_id',
               existing_type=mysql.CHAR(length=36),
               nullable=True)
    op.add_column('ctfs', sa.Column('is_flag_regex', sa.Boolean(), nullable=True))
    op.add_column('ctfs', sa.Column('created_by_id', sa.CHAR(length=36), nullable=True))
    op.add_column('ctfs', sa.Column('updated_by_id', sa.CHAR(length=36), nullable=True))
    op.create_foreign_key(None, 'ctfs', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'ctfs', 'users', ['updated_by_id'], ['id'])
    op.alter_column('writeups', 'ctf_id',
               existing_type=mysql.CHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('writeups', 'ctf_id',
               existing_type=mysql.CHAR(length=36),
               nullable=False)
    op.drop_constraint(None, 'ctfs', type_='foreignkey')
    op.drop_constraint(None, 'ctfs', type_='foreignkey')
    op.drop_column('ctfs', 'updated_by_id')
    op.drop_column('ctfs', 'created_by_id')
    op.drop_column('ctfs', 'is_flag_regex')
    op.alter_column('attachments', 'ctf_id',
               existing_type=mysql.CHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
