"""add_is_flag_regex_column_to_ctfs

Revision ID: e2f72b1ae5f3
Revises: 73af1314d471
Create Date: 2025-12-30 10:02:36.532881

Safe on fresh Postgres (Render): if base tables do not exist yet (empty
initial revision 73af1314d471), this revision is a no-op. Schema creation
is handled later by a9b8c7d6e5f4. Existing MySQL/Postgres DBs that already
have the tables keep the original alters/adds (idempotent on columns).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e2f72b1ae5f3"
down_revision: Union[str, None] = "73af1314d471"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_names() -> set[str]:
    return set(sa.inspect(op.get_bind()).get_table_names())


def _columns(table: str) -> set[str]:
    bind = op.get_bind()
    return {c["name"] for c in sa.inspect(bind).get_columns(table)}


def upgrade() -> None:
    tables = _table_names()
    # Fresh Render DB: 73af is empty; tables appear only in a9b8 (after f1a8).
    required = {"attachments", "ctfs", "writeups", "users"}
    if not required.issubset(tables):
        return

    cols = _columns("ctfs")
    if "attachments" in tables:
        op.alter_column(
            "attachments",
            "ctf_id",
            existing_type=sa.CHAR(length=36),
            nullable=True,
        )
    if "is_flag_regex" not in cols:
        op.add_column("ctfs", sa.Column("is_flag_regex", sa.Boolean(), nullable=True))
    if "created_by_id" not in cols:
        op.add_column("ctfs", sa.Column("created_by_id", sa.CHAR(length=36), nullable=True))
    if "updated_by_id" not in cols:
        op.add_column("ctfs", sa.Column("updated_by_id", sa.CHAR(length=36), nullable=True))

    # FKs: create only when columns exist (batch may already have them from a9b8 path)
    existing_fks = {
        fk["constrained_columns"][0]
        for fk in sa.inspect(op.get_bind()).get_foreign_keys("ctfs")
        if fk.get("constrained_columns")
    }
    if "created_by_id" in _columns("ctfs") and "created_by_id" not in existing_fks:
        op.create_foreign_key(None, "ctfs", "users", ["created_by_id"], ["id"])
    if "updated_by_id" in _columns("ctfs") and "updated_by_id" not in existing_fks:
        op.create_foreign_key(None, "ctfs", "users", ["updated_by_id"], ["id"])

    if "writeups" in tables:
        op.alter_column(
            "writeups",
            "ctf_id",
            existing_type=sa.CHAR(length=36),
            nullable=True,
        )


def downgrade() -> None:
    tables = _table_names()
    if not {"attachments", "ctfs", "writeups"}.issubset(tables):
        return
    op.alter_column(
        "writeups",
        "ctf_id",
        existing_type=sa.CHAR(length=36),
        nullable=False,
    )
    # Best-effort FK drops (names are autogenerated and dialect-specific)
    for fk in list(sa.inspect(op.get_bind()).get_foreign_keys("ctfs")):
        cols = fk.get("constrained_columns") or []
        if cols and cols[0] in {"created_by_id", "updated_by_id"} and fk.get("name"):
            op.drop_constraint(fk["name"], "ctfs", type_="foreignkey")
    cols = _columns("ctfs")
    if "updated_by_id" in cols:
        op.drop_column("ctfs", "updated_by_id")
    if "created_by_id" in cols:
        op.drop_column("ctfs", "created_by_id")
    if "is_flag_regex" in cols:
        op.drop_column("ctfs", "is_flag_regex")
    op.alter_column(
        "attachments",
        "ctf_id",
        existing_type=sa.CHAR(length=36),
        nullable=False,
    )
